apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-dsjdqyil 
  janus-idp.io/tekton: go-dsjdqyil
  backstage.io/kubernetes-id: go-dsjdqyil
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-dsjdqyil
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml